// Code generated by `go generate`. DO NOT EDIT.
// source: server/internal/gen/callbacks.go.tmpl
package server

import (
	"github.com/mark3labs/mcp-go/mcp"
)

// OnBeforeAnyCallbackFunc is a function that is called after the request is
// parsed but before the method is called.
type OnBeforeAnyCallbackFunc func(id any, method mcp.MCPMethod, message any)

// OnAfterAnyCallbackFunc is a callback that will be called after the request
// successfully generates a result, but before the result is sent to the client.
type OnAfterAnyCallbackFunc func(id any, method mcp.MCPMethod, message any, result any)

// OnErrorCallbackFunc is a callback that will be called when an error occurs,
// either during the request parsing or the method execution.
type OnErrorCallbackFunc func(id any, method mcp.MCPMethod, message any, err error)

type OnBeforeInitializeFunc func(id any, message *mcp.InitializeRequest)
type OnAfterInitializeFunc func(id any, message *mcp.InitializeRequest, result *mcp.InitializeResult)

type OnBeforePingFunc func(id any, message *mcp.PingRequest)
type OnAfterPingFunc func(id any, message *mcp.PingRequest, result *mcp.EmptyResult)

type OnBeforeListResourcesFunc func(id any, message *mcp.ListResourcesRequest)
type OnAfterListResourcesFunc func(id any, message *mcp.ListResourcesRequest, result *mcp.ListResourcesResult)

type OnBeforeListResourceTemplatesFunc func(id any, message *mcp.ListResourceTemplatesRequest)
type OnAfterListResourceTemplatesFunc func(id any, message *mcp.ListResourceTemplatesRequest, result *mcp.ListResourceTemplatesResult)

type OnBeforeReadResourceFunc func(id any, message *mcp.ReadResourceRequest)
type OnAfterReadResourceFunc func(id any, message *mcp.ReadResourceRequest, result *mcp.ReadResourceResult)

type OnBeforeListPromptsFunc func(id any, message *mcp.ListPromptsRequest)
type OnAfterListPromptsFunc func(id any, message *mcp.ListPromptsRequest, result *mcp.ListPromptsResult)

type OnBeforeGetPromptFunc func(id any, message *mcp.GetPromptRequest)
type OnAfterGetPromptFunc func(id any, message *mcp.GetPromptRequest, result *mcp.GetPromptResult)

type OnBeforeListToolsFunc func(id any, message *mcp.ListToolsRequest)
type OnAfterListToolsFunc func(id any, message *mcp.ListToolsRequest, result *mcp.ListToolsResult)

type OnBeforeCallToolFunc func(id any, message *mcp.CallToolRequest)
type OnAfterCallToolFunc func(id any, message *mcp.CallToolRequest, result *mcp.CallToolResult)

type Callbacks struct {
	OnBeforeAny                   []OnBeforeAnyCallbackFunc
	OnAfterAny                    []OnAfterAnyCallbackFunc
	OnError                       []OnErrorCallbackFunc
	OnBeforeInitialize            []OnBeforeInitializeFunc
	OnAfterInitialize             []OnAfterInitializeFunc
	OnBeforePing                  []OnBeforePingFunc
	OnAfterPing                   []OnAfterPingFunc
	OnBeforeListResources         []OnBeforeListResourcesFunc
	OnAfterListResources          []OnAfterListResourcesFunc
	OnBeforeListResourceTemplates []OnBeforeListResourceTemplatesFunc
	OnAfterListResourceTemplates  []OnAfterListResourceTemplatesFunc
	OnBeforeReadResource          []OnBeforeReadResourceFunc
	OnAfterReadResource           []OnAfterReadResourceFunc
	OnBeforeListPrompts           []OnBeforeListPromptsFunc
	OnAfterListPrompts            []OnAfterListPromptsFunc
	OnBeforeGetPrompt             []OnBeforeGetPromptFunc
	OnAfterGetPrompt              []OnAfterGetPromptFunc
	OnBeforeListTools             []OnBeforeListToolsFunc
	OnAfterListTools              []OnAfterListToolsFunc
	OnBeforeCallTool              []OnBeforeCallToolFunc
	OnAfterCallTool               []OnAfterCallToolFunc
}

func (c *Callbacks) AddBeforeAny(callback OnBeforeAnyCallbackFunc) {
	c.OnBeforeAny = append(c.OnBeforeAny, callback)
}

func (c *Callbacks) AddAfterAny(callback OnAfterAnyCallbackFunc) {
	c.OnAfterAny = append(c.OnAfterAny, callback)
}

func (c *Callbacks) AddOnError(callback OnErrorCallbackFunc) {
	c.OnError = append(c.OnError, callback)
}

func (c *Callbacks) beforeAny(id any, method mcp.MCPMethod, message any) {
	if c == nil {
		return
	}
	for _, callback := range c.OnBeforeAny {
		callback(id, method, &message)
	}
}

func (c *Callbacks) afterAny(id any, method mcp.MCPMethod, message any, result any) {
	if c == nil {
		return
	}
	for _, callback := range c.OnAfterAny {
		callback(id, method, &message, result)
	}
}

func (c *Callbacks) onError(id any, method mcp.MCPMethod, message any, err error) {
	if c == nil {
		return
	}
	for _, callback := range c.OnError {
		callback(id, method, message, err)
	}
}
func (c *Callbacks) AddBeforeInitialize(callback OnBeforeInitializeFunc) {
	c.OnBeforeInitialize = append(c.OnBeforeInitialize, callback)
}

func (c *Callbacks) AddAfterInitialize(callback OnAfterInitializeFunc) {
	c.OnAfterInitialize = append(c.OnAfterInitialize, callback)
}

func (c *Callbacks) beforeInitialize(id any, message *mcp.InitializeRequest) {
	c.beforeAny(id, mcp.MethodInitialize, message)
	if c == nil {
		return
	}
	for _, callback := range c.OnBeforeInitialize {
		callback(id, message)
	}
}

func (c *Callbacks) afterInitialize(id any, message *mcp.InitializeRequest, result *mcp.InitializeResult) {
	c.afterAny(id, mcp.MethodInitialize, message, result)
	if c == nil {
		return
	}
	for _, callback := range c.OnAfterInitialize {
		callback(id, message, result)
	}
}
func (c *Callbacks) AddBeforePing(callback OnBeforePingFunc) {
	c.OnBeforePing = append(c.OnBeforePing, callback)
}

func (c *Callbacks) AddAfterPing(callback OnAfterPingFunc) {
	c.OnAfterPing = append(c.OnAfterPing, callback)
}

func (c *Callbacks) beforePing(id any, message *mcp.PingRequest) {
	c.beforeAny(id, mcp.MethodPing, message)
	if c == nil {
		return
	}
	for _, callback := range c.OnBeforePing {
		callback(id, message)
	}
}

func (c *Callbacks) afterPing(id any, message *mcp.PingRequest, result *mcp.EmptyResult) {
	c.afterAny(id, mcp.MethodPing, message, result)
	if c == nil {
		return
	}
	for _, callback := range c.OnAfterPing {
		callback(id, message, result)
	}
}
func (c *Callbacks) AddBeforeListResources(callback OnBeforeListResourcesFunc) {
	c.OnBeforeListResources = append(c.OnBeforeListResources, callback)
}

func (c *Callbacks) AddAfterListResources(callback OnAfterListResourcesFunc) {
	c.OnAfterListResources = append(c.OnAfterListResources, callback)
}

func (c *Callbacks) beforeListResources(id any, message *mcp.ListResourcesRequest) {
	c.beforeAny(id, mcp.MethodResourcesList, message)
	if c == nil {
		return
	}
	for _, callback := range c.OnBeforeListResources {
		callback(id, message)
	}
}

func (c *Callbacks) afterListResources(id any, message *mcp.ListResourcesRequest, result *mcp.ListResourcesResult) {
	c.afterAny(id, mcp.MethodResourcesList, message, result)
	if c == nil {
		return
	}
	for _, callback := range c.OnAfterListResources {
		callback(id, message, result)
	}
}
func (c *Callbacks) AddBeforeListResourceTemplates(callback OnBeforeListResourceTemplatesFunc) {
	c.OnBeforeListResourceTemplates = append(c.OnBeforeListResourceTemplates, callback)
}

func (c *Callbacks) AddAfterListResourceTemplates(callback OnAfterListResourceTemplatesFunc) {
	c.OnAfterListResourceTemplates = append(c.OnAfterListResourceTemplates, callback)
}

func (c *Callbacks) beforeListResourceTemplates(id any, message *mcp.ListResourceTemplatesRequest) {
	c.beforeAny(id, mcp.MethodResourcesTemplatesList, message)
	if c == nil {
		return
	}
	for _, callback := range c.OnBeforeListResourceTemplates {
		callback(id, message)
	}
}

func (c *Callbacks) afterListResourceTemplates(id any, message *mcp.ListResourceTemplatesRequest, result *mcp.ListResourceTemplatesResult) {
	c.afterAny(id, mcp.MethodResourcesTemplatesList, message, result)
	if c == nil {
		return
	}
	for _, callback := range c.OnAfterListResourceTemplates {
		callback(id, message, result)
	}
}
func (c *Callbacks) AddBeforeReadResource(callback OnBeforeReadResourceFunc) {
	c.OnBeforeReadResource = append(c.OnBeforeReadResource, callback)
}

func (c *Callbacks) AddAfterReadResource(callback OnAfterReadResourceFunc) {
	c.OnAfterReadResource = append(c.OnAfterReadResource, callback)
}

func (c *Callbacks) beforeReadResource(id any, message *mcp.ReadResourceRequest) {
	c.beforeAny(id, mcp.MethodResourcesRead, message)
	if c == nil {
		return
	}
	for _, callback := range c.OnBeforeReadResource {
		callback(id, message)
	}
}

func (c *Callbacks) afterReadResource(id any, message *mcp.ReadResourceRequest, result *mcp.ReadResourceResult) {
	c.afterAny(id, mcp.MethodResourcesRead, message, result)
	if c == nil {
		return
	}
	for _, callback := range c.OnAfterReadResource {
		callback(id, message, result)
	}
}
func (c *Callbacks) AddBeforeListPrompts(callback OnBeforeListPromptsFunc) {
	c.OnBeforeListPrompts = append(c.OnBeforeListPrompts, callback)
}

func (c *Callbacks) AddAfterListPrompts(callback OnAfterListPromptsFunc) {
	c.OnAfterListPrompts = append(c.OnAfterListPrompts, callback)
}

func (c *Callbacks) beforeListPrompts(id any, message *mcp.ListPromptsRequest) {
	c.beforeAny(id, mcp.MethodPromptsList, message)
	if c == nil {
		return
	}
	for _, callback := range c.OnBeforeListPrompts {
		callback(id, message)
	}
}

func (c *Callbacks) afterListPrompts(id any, message *mcp.ListPromptsRequest, result *mcp.ListPromptsResult) {
	c.afterAny(id, mcp.MethodPromptsList, message, result)
	if c == nil {
		return
	}
	for _, callback := range c.OnAfterListPrompts {
		callback(id, message, result)
	}
}
func (c *Callbacks) AddBeforeGetPrompt(callback OnBeforeGetPromptFunc) {
	c.OnBeforeGetPrompt = append(c.OnBeforeGetPrompt, callback)
}

func (c *Callbacks) AddAfterGetPrompt(callback OnAfterGetPromptFunc) {
	c.OnAfterGetPrompt = append(c.OnAfterGetPrompt, callback)
}

func (c *Callbacks) beforeGetPrompt(id any, message *mcp.GetPromptRequest) {
	c.beforeAny(id, mcp.MethodPromptsGet, message)
	if c == nil {
		return
	}
	for _, callback := range c.OnBeforeGetPrompt {
		callback(id, message)
	}
}

func (c *Callbacks) afterGetPrompt(id any, message *mcp.GetPromptRequest, result *mcp.GetPromptResult) {
	c.afterAny(id, mcp.MethodPromptsGet, message, result)
	if c == nil {
		return
	}
	for _, callback := range c.OnAfterGetPrompt {
		callback(id, message, result)
	}
}
func (c *Callbacks) AddBeforeListTools(callback OnBeforeListToolsFunc) {
	c.OnBeforeListTools = append(c.OnBeforeListTools, callback)
}

func (c *Callbacks) AddAfterListTools(callback OnAfterListToolsFunc) {
	c.OnAfterListTools = append(c.OnAfterListTools, callback)
}

func (c *Callbacks) beforeListTools(id any, message *mcp.ListToolsRequest) {
	c.beforeAny(id, mcp.MethodToolsList, message)
	if c == nil {
		return
	}
	for _, callback := range c.OnBeforeListTools {
		callback(id, message)
	}
}

func (c *Callbacks) afterListTools(id any, message *mcp.ListToolsRequest, result *mcp.ListToolsResult) {
	c.afterAny(id, mcp.MethodToolsList, message, result)
	if c == nil {
		return
	}
	for _, callback := range c.OnAfterListTools {
		callback(id, message, result)
	}
}
func (c *Callbacks) AddBeforeCallTool(callback OnBeforeCallToolFunc) {
	c.OnBeforeCallTool = append(c.OnBeforeCallTool, callback)
}

func (c *Callbacks) AddAfterCallTool(callback OnAfterCallToolFunc) {
	c.OnAfterCallTool = append(c.OnAfterCallTool, callback)
}

func (c *Callbacks) beforeCallTool(id any, message *mcp.CallToolRequest) {
	c.beforeAny(id, mcp.MethodToolsCall, message)
	if c == nil {
		return
	}
	for _, callback := range c.OnBeforeCallTool {
		callback(id, message)
	}
}

func (c *Callbacks) afterCallTool(id any, message *mcp.CallToolRequest, result *mcp.CallToolResult) {
	c.afterAny(id, mcp.MethodToolsCall, message, result)
	if c == nil {
		return
	}
	for _, callback := range c.OnAfterCallTool {
		callback(id, message, result)
	}
}
